/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package RestaurantManagementSystem;

import java.awt.Frame;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author 20112
 */
public class adminframe extends javax.swing.JFrame {

    /**
     * Creates new form adminframe
     */
    
     int id, row;
    user u = new user();
    Employee e = new Employee();    
    Meals m = new Meals();
    dbconnection c = new dbconnection();
    Admin a = new Admin ();
    Offer o = new Offer();
    int roleID;
    
    
    public adminframe() {
        initComponents();
         //show_admin();
       
         
         
         
    }
  private void clear_data(){
    emp_id.setText(null);
    emp_name.setText(null);
   emp_pass.setText(null);
    
    
  }
   private void clear_delete() {
    id_delete.setText(null);   
   }
   private void clear_search(){
       search_idemp.setText(null);   
   }
    
private void clear_update(){
    e_id.setText(null); 
    e_name.setText(null);
    e_pass.setText(null);
}
private void clear_addMeal(){
    meal_id.setText(null);
    meal_name.setText(null);
    meal_price.setText(null);
   meal_quan.setText(null);
   a_id.setText(null);
    
}
private void clear_deleteMeal(){
id_delete1.setText(null); 
}
private void clear_searchMeal(){
    search_id1.setText(null); 
}
private void clear_updataMeal(){
    m_id.setText(null); 
    m_name.setText(null); 
    m_price.setText(null); 
    m_quan.setText(null); 
    
}
private void clear_offer(){
    ofID.setText(null); 
    offerDetalis.setText(null); 
    admID.setText(null);
}
private void clear_report(){
    id2.setText(null); 
    description.setText(null); 
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        admin = new javax.swing.JTabbedPane();
        employee = new javax.swing.JPanel();
        emp_mange = new javax.swing.JTabbedPane();
        add_emp = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        emp_id = new javax.swing.JTextField();
        emp_name = new javax.swing.JTextField();
        emp_add = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        emp_pass = new javax.swing.JTextField();
        delete_emp = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        id_delete = new javax.swing.JTextField();
        delete = new javax.swing.JButton();
        list_emp = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        emp_table = new javax.swing.JTable();
        listButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        search_cust1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        search_emp = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        search_idemp = new javax.swing.JTextField();
        searchEmployee = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        e_id = new javax.swing.JTextField();
        e_name = new javax.swing.JTextField();
        e_pass = new javax.swing.JPasswordField();
        updateEmployee = new javax.swing.JButton();
        back = new javax.swing.JButton();
        Meal = new javax.swing.JPanel();
        meals = new javax.swing.JTabbedPane();
        add_emp1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        meal_id = new javax.swing.JTextField();
        meal_name = new javax.swing.JTextField();
        meal_add1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        meal_price = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        meal_quan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        a_id = new javax.swing.JTextField();
        delete_cust2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        id_delete1 = new javax.swing.JTextField();
        delete_meal = new javax.swing.JButton();
        list_cust2 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        meal_table2 = new javax.swing.JTable();
        update_button = new javax.swing.JButton();
        list_button = new javax.swing.JButton();
        delet_button = new javax.swing.JButton();
        search_cust2 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        search_table1 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        search_id1 = new javax.swing.JTextField();
        search_meal = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        m_name = new javax.swing.JTextField();
        m_id = new javax.swing.JTextField();
        update_meal = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        m_price = new javax.swing.JTextField();
        m_quan = new javax.swing.JTextField();
        offer = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ofID = new javax.swing.JTextField();
        offerDetalis = new javax.swing.JTextField();
        admID = new javax.swing.JTextField();
        add_offer = new javax.swing.JButton();
        Report1 = new javax.swing.JPanel();
        custRadio = new javax.swing.JRadioButton();
        empRadio = new javax.swing.JRadioButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        reportTable = new javax.swing.JTable();
        id2 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        reportButton = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        admin.setBackground(new java.awt.Color(0, 102, 153));
        admin.setForeground(new java.awt.Color(255, 255, 255));
        admin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        admin.setMinimumSize(new java.awt.Dimension(595, 471));
        admin.setPreferredSize(new java.awt.Dimension(643, 489));
        admin.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                adminAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        employee.setBackground(new java.awt.Color(0, 102, 153));
        employee.setMinimumSize(new java.awt.Dimension(594, 430));
        employee.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emp_mange.setBackground(new java.awt.Color(0, 102, 153));
        emp_mange.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        add_emp.setBackground(new java.awt.Color(255, 255, 255));
        add_emp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Teko SemiBold", 0, 17)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 153));
        jLabel9.setText("Employee ID");
        add_emp.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 49, -1, 30));

        jLabel10.setFont(new java.awt.Font("Teko SemiBold", 0, 17)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 153));
        jLabel10.setText("Employee Name");
        add_emp.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 110, 105, -1));
        add_emp.add(emp_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 49, 121, 30));

        emp_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_nameActionPerformed(evt);
            }
        });
        add_emp.add(emp_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 113, 121, 31));

        emp_add.setFont(new java.awt.Font("Teko SemiBold", 0, 17)); // NOI18N
        emp_add.setForeground(new java.awt.Color(0, 102, 153));
        emp_add.setText("Add");
        emp_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_addActionPerformed(evt);
            }
        });
        add_emp.add(emp_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 236, 102, 45));

        jLabel1.setFont(new java.awt.Font("Teko SemiBold", 0, 17)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 153));
        jLabel1.setText("Employee Password");
        add_emp.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 162, -1, -1));
        add_emp.add(emp_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 162, 121, 26));

        emp_mange.addTab("Add ", add_emp);

        delete_emp.setBackground(new java.awt.Color(255, 255, 255));
        delete_emp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Teko SemiBold", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 153));
        jLabel12.setText("Employee ID");
        delete_emp.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        id_delete.setFont(new java.awt.Font("Teko SemiBold", 0, 18)); // NOI18N
        id_delete.setForeground(new java.awt.Color(0, 102, 153));
        delete_emp.add(id_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 100, -1));

        delete.setFont(new java.awt.Font("Teko SemiBold", 0, 18)); // NOI18N
        delete.setForeground(new java.awt.Color(0, 102, 153));
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        delete_emp.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 96, 49));

        emp_mange.addTab("Delete", delete_emp);

        list_emp.setBackground(new java.awt.Color(255, 255, 255));

        emp_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Name", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(emp_table);

        listButton.setFont(new java.awt.Font("Teko SemiBold", 0, 18)); // NOI18N
        listButton.setForeground(new java.awt.Color(0, 102, 153));
        listButton.setText("List");
        listButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listButtonActionPerformed(evt);
            }
        });

        updateButton.setFont(new java.awt.Font("Teko SemiBold", 0, 18)); // NOI18N
        updateButton.setForeground(new java.awt.Color(0, 102, 153));
        updateButton.setText("update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("Teko SemiBold", 0, 18)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(0, 102, 153));
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout list_empLayout = new javax.swing.GroupLayout(list_emp);
        list_emp.setLayout(list_empLayout);
        list_empLayout.setHorizontalGroup(
            list_empLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(list_empLayout.createSequentialGroup()
                .addGroup(list_empLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(list_empLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(updateButton)
                        .addGap(66, 66, 66)
                        .addComponent(listButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(deleteButton))
                    .addGroup(list_empLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        list_empLayout.setVerticalGroup(
            list_empLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(list_empLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(list_empLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        emp_mange.addTab("List", list_emp);

        search_cust1.setBackground(new java.awt.Color(255, 255, 255));

        search_emp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Name ", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(search_emp);

        jLabel20.setFont(new java.awt.Font("Teko SemiBold", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 102, 153));
        jLabel20.setText("Employee ID");

        search_idemp.setFont(new java.awt.Font("Teko SemiBold", 0, 18)); // NOI18N
        search_idemp.setForeground(new java.awt.Color(0, 102, 153));

        searchEmployee.setFont(new java.awt.Font("Teko SemiBold", 0, 18)); // NOI18N
        searchEmployee.setForeground(new java.awt.Color(0, 102, 153));
        searchEmployee.setText("Search");
        searchEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchEmployeeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout search_cust1Layout = new javax.swing.GroupLayout(search_cust1);
        search_cust1.setLayout(search_cust1Layout);
        search_cust1Layout.setHorizontalGroup(
            search_cust1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_cust1Layout.createSequentialGroup()
                .addGroup(search_cust1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(search_cust1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel20)
                        .addGap(49, 49, 49)
                        .addComponent(search_idemp, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(search_cust1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(search_cust1Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(searchEmployee)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        search_cust1Layout.setVerticalGroup(
            search_cust1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_cust1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(search_cust1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search_idemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addComponent(searchEmployee)
                .addContainerGap())
        );

        emp_mange.addTab("Search", search_cust1);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Teko SemiBold", 0, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 153));
        jLabel17.setText("Employee ID");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        jLabel18.setFont(new java.awt.Font("Teko SemiBold", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 102, 153));
        jLabel18.setText("Employee Name");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        jLabel19.setFont(new java.awt.Font("Teko SemiBold", 0, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 102, 153));
        jLabel19.setText("Employee Password ");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        e_id.setEditable(false);
        e_id.setFont(new java.awt.Font("Teko SemiBold", 0, 16)); // NOI18N
        e_id.setForeground(new java.awt.Color(0, 102, 153));
        jPanel1.add(e_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 143, -1));

        e_name.setFont(new java.awt.Font("Teko SemiBold", 0, 16)); // NOI18N
        e_name.setForeground(new java.awt.Color(0, 102, 153));
        e_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_nameActionPerformed(evt);
            }
        });
        jPanel1.add(e_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 143, -1));

        e_pass.setFont(new java.awt.Font("Teko SemiBold", 0, 16)); // NOI18N
        e_pass.setForeground(new java.awt.Color(0, 102, 153));
        e_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_passActionPerformed(evt);
            }
        });
        jPanel1.add(e_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 143, -1));

        updateEmployee.setFont(new java.awt.Font("Teko SemiBold", 0, 16)); // NOI18N
        updateEmployee.setForeground(new java.awt.Color(0, 102, 153));
        updateEmployee.setText("Update");
        updateEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateEmployeeActionPerformed(evt);
            }
        });
        jPanel1.add(updateEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, -1));

        emp_mange.addTab("Update", jPanel1);

        employee.add(emp_mange, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 26, -1, 330));

        back.setFont(new java.awt.Font("Teko SemiBold", 0, 24)); // NOI18N
        back.setForeground(new java.awt.Color(0, 102, 153));
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        employee.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        admin.addTab("Employee", employee);

        Meal.setBackground(new java.awt.Color(0, 102, 153));

        meals.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        add_emp1.setBackground(new java.awt.Color(255, 255, 255));
        add_emp1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Teko SemiBold", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 153));
        jLabel11.setText("Meal ID");
        add_emp1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, 30));

        jLabel14.setFont(new java.awt.Font("Teko SemiBold", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 153));
        jLabel14.setText("Meal Name");
        add_emp1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 88, 26));

        meal_id.setFont(new java.awt.Font("Teko SemiBold", 0, 15)); // NOI18N
        meal_id.setForeground(new java.awt.Color(0, 102, 153));
        meal_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meal_idActionPerformed(evt);
            }
        });
        add_emp1.add(meal_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 121, -1));

        meal_name.setFont(new java.awt.Font("Teko SemiBold", 0, 15)); // NOI18N
        meal_name.setForeground(new java.awt.Color(0, 102, 153));
        meal_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meal_nameActionPerformed(evt);
            }
        });
        add_emp1.add(meal_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 121, -1));

        meal_add1.setFont(new java.awt.Font("Teko SemiBold", 0, 18)); // NOI18N
        meal_add1.setForeground(new java.awt.Color(0, 102, 153));
        meal_add1.setText("Add");
        meal_add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meal_add1ActionPerformed(evt);
            }
        });
        add_emp1.add(meal_add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 76, 32));

        jLabel2.setFont(new java.awt.Font("Teko SemiBold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 153));
        jLabel2.setText("Meal Price");
        add_emp1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        meal_price.setFont(new java.awt.Font("Teko SemiBold", 0, 15)); // NOI18N
        meal_price.setForeground(new java.awt.Color(0, 102, 153));
        meal_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meal_priceActionPerformed(evt);
            }
        });
        add_emp1.add(meal_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 121, -1));

        jLabel3.setFont(new java.awt.Font("Teko SemiBold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 153));
        jLabel3.setText("Meal Quantity");
        add_emp1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        meal_quan.setFont(new java.awt.Font("Teko SemiBold", 0, 15)); // NOI18N
        meal_quan.setForeground(new java.awt.Color(0, 102, 153));
        meal_quan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meal_quanActionPerformed(evt);
            }
        });
        add_emp1.add(meal_quan, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 121, -1));

        jLabel4.setFont(new java.awt.Font("Teko SemiBold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 153));
        add_emp1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 237, -1, -1));

        jLabel24.setFont(new java.awt.Font("Teko SemiBold", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 102, 153));
        jLabel24.setText("Admin ID");
        add_emp1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        a_id.setFont(new java.awt.Font("Teko SemiBold", 0, 16)); // NOI18N
        a_id.setForeground(new java.awt.Color(0, 102, 153));
        add_emp1.add(a_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 60, 30));

        meals.addTab("Add", add_emp1);

        delete_cust2.setBackground(new java.awt.Color(255, 255, 255));
        delete_cust2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Teko SemiBold", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 102, 153));
        jLabel15.setText("Meal ID");
        delete_cust2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 59, -1));

        id_delete1.setFont(new java.awt.Font("Teko SemiBold", 0, 18)); // NOI18N
        id_delete1.setForeground(new java.awt.Color(0, 102, 153));
        delete_cust2.add(id_delete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 100, -1));

        delete_meal.setFont(new java.awt.Font("Teko SemiBold", 0, 18)); // NOI18N
        delete_meal.setForeground(new java.awt.Color(0, 102, 153));
        delete_meal.setText("Delete");
        delete_meal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_mealActionPerformed(evt);
            }
        });
        delete_cust2.add(delete_meal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));

        meals.addTab("Delete", delete_cust2);

        list_cust2.setBackground(new java.awt.Color(255, 255, 255));
        list_cust2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        meal_table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Price ", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(meal_table2);

        list_cust2.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 470, 94));

        update_button.setFont(new java.awt.Font("Teko SemiBold", 0, 18)); // NOI18N
        update_button.setForeground(new java.awt.Color(0, 102, 153));
        update_button.setText("update");
        update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_buttonActionPerformed(evt);
            }
        });
        list_cust2.add(update_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 198, -1, 37));

        list_button.setFont(new java.awt.Font("Teko SemiBold", 0, 18)); // NOI18N
        list_button.setForeground(new java.awt.Color(0, 102, 153));
        list_button.setText("List");
        list_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_buttonActionPerformed(evt);
            }
        });
        list_cust2.add(list_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 198, 76, 37));

        delet_button.setFont(new java.awt.Font("Teko SemiBold", 0, 18)); // NOI18N
        delet_button.setForeground(new java.awt.Color(0, 102, 153));
        delet_button.setText("delete");
        delet_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delet_buttonActionPerformed(evt);
            }
        });
        list_cust2.add(delet_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 198, -1, 37));

        meals.addTab("List", list_cust2);

        search_cust2.setBackground(new java.awt.Color(255, 255, 255));
        search_cust2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search_table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Price ", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane7.setViewportView(search_table1);

        search_cust2.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 439, 94));

        jLabel13.setFont(new java.awt.Font("Teko SemiBold", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 153));
        jLabel13.setText("Meal ID");
        search_cust2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 91, 30));

        search_id1.setFont(new java.awt.Font("Teko SemiBold", 0, 18)); // NOI18N
        search_id1.setForeground(new java.awt.Color(0, 102, 153));
        search_id1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_id1ActionPerformed(evt);
            }
        });
        search_cust2.add(search_id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 95, 30));

        search_meal.setFont(new java.awt.Font("Teko SemiBold", 0, 18)); // NOI18N
        search_meal.setForeground(new java.awt.Color(0, 102, 153));
        search_meal.setText("Search");
        search_meal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_mealActionPerformed(evt);
            }
        });
        search_cust2.add(search_meal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 101, 47));

        meals.addTab("Search", search_cust2);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Teko SemiBold", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 102, 153));
        jLabel21.setText("Meal ID");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        jLabel22.setFont(new java.awt.Font("Teko SemiBold", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 102, 153));
        jLabel22.setText("Meal Name");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        jLabel23.setFont(new java.awt.Font("Teko SemiBold", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 102, 153));
        jLabel23.setText("Meal Price ");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        m_name.setFont(new java.awt.Font("Teko SemiBold", 0, 16)); // NOI18N
        m_name.setForeground(new java.awt.Color(0, 102, 153));
        m_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_nameActionPerformed(evt);
            }
        });
        jPanel2.add(m_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 130, -1));

        m_id.setEditable(false);
        m_id.setFont(new java.awt.Font("Teko SemiBold", 0, 16)); // NOI18N
        m_id.setForeground(new java.awt.Color(0, 102, 153));
        jPanel2.add(m_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 130, -1));

        update_meal.setFont(new java.awt.Font("Teko SemiBold", 0, 18)); // NOI18N
        update_meal.setForeground(new java.awt.Color(0, 102, 153));
        update_meal.setText("Update");
        update_meal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_mealActionPerformed(evt);
            }
        });
        jPanel2.add(update_meal, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        jLabel16.setFont(new java.awt.Font("Teko SemiBold", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 102, 153));
        jLabel16.setText("Meal Quantity");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

        m_price.setFont(new java.awt.Font("Teko SemiBold", 0, 16)); // NOI18N
        m_price.setForeground(new java.awt.Color(0, 102, 153));
        m_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_priceActionPerformed(evt);
            }
        });
        jPanel2.add(m_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 130, 30));

        m_quan.setFont(new java.awt.Font("Teko SemiBold", 0, 16)); // NOI18N
        m_quan.setForeground(new java.awt.Color(0, 102, 153));
        jPanel2.add(m_quan, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 130, 30));

        meals.addTab("Update", jPanel2);

        javax.swing.GroupLayout MealLayout = new javax.swing.GroupLayout(Meal);
        Meal.setLayout(MealLayout);
        MealLayout.setHorizontalGroup(
            MealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MealLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(meals, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );
        MealLayout.setVerticalGroup(
            MealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MealLayout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(meals, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );

        admin.addTab("Meals", Meal);

        offer.setBackground(new java.awt.Color(0, 102, 153));
        offer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Teko SemiBold", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Offer ID");
        offer.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

        jLabel6.setFont(new java.awt.Font("Teko SemiBold", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Offer Details");
        offer.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 90, -1));

        jLabel8.setFont(new java.awt.Font("Teko SemiBold", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Admin ID");
        offer.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        ofID.setFont(new java.awt.Font("Teko SemiBold", 0, 16)); // NOI18N
        ofID.setForeground(new java.awt.Color(0, 102, 153));
        ofID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ofIDActionPerformed(evt);
            }
        });
        offer.add(ofID, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 90, 30));

        offerDetalis.setFont(new java.awt.Font("Teko SemiBold", 0, 16)); // NOI18N
        offerDetalis.setForeground(new java.awt.Color(0, 102, 153));
        offer.add(offerDetalis, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 120, 40));

        admID.setFont(new java.awt.Font("Teko SemiBold", 0, 16)); // NOI18N
        admID.setForeground(new java.awt.Color(0, 102, 153));
        admID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admIDActionPerformed(evt);
            }
        });
        offer.add(admID, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 80, 30));

        add_offer.setFont(new java.awt.Font("Teko SemiBold", 1, 18)); // NOI18N
        add_offer.setForeground(new java.awt.Color(0, 102, 153));
        add_offer.setText("Add Offer");
        add_offer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_offerActionPerformed(evt);
            }
        });
        offer.add(add_offer, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, -1, -1));

        admin.addTab("Offer", offer);

        Report1.setBackground(new java.awt.Color(0, 102, 153));
        Report1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        custRadio.setBackground(new java.awt.Color(0, 102, 153));
        buttonGroup1.add(custRadio);
        custRadio.setFont(new java.awt.Font("Teko SemiBold", 1, 18)); // NOI18N
        custRadio.setForeground(new java.awt.Color(255, 255, 255));
        custRadio.setText("Customer");
        custRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custRadioActionPerformed(evt);
            }
        });
        Report1.add(custRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        empRadio.setBackground(new java.awt.Color(0, 102, 153));
        buttonGroup1.add(empRadio);
        empRadio.setFont(new java.awt.Font("Teko SemiBold", 1, 18)); // NOI18N
        empRadio.setForeground(new java.awt.Color(255, 255, 255));
        empRadio.setText("Employee");
        empRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empRadioActionPerformed(evt);
            }
        });
        Report1.add(empRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        reportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Password/Type", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane9.setViewportView(reportTable);

        Report1.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 470, 100));
        Report1.add(id2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 100, -1));

        jLabel41.setFont(new java.awt.Font("Teko SemiBold", 1, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("ID");
        Report1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        jLabel42.setFont(new java.awt.Font("Teko SemiBold", 1, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Description");
        Report1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, -1));

        reportButton.setBackground(new java.awt.Color(255, 255, 255));
        reportButton.setFont(new java.awt.Font("Teko SemiBold", 1, 18)); // NOI18N
        reportButton.setForeground(new java.awt.Color(0, 102, 153));
        reportButton.setText("Report");
        reportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportButtonActionPerformed(evt);
            }
        });
        Report1.add(reportButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, -1));

        description.setColumns(20);
        description.setRows(5);
        jScrollPane10.setViewportView(description);

        Report1.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 100, 70));

        admin.addTab("Report", Report1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(admin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_adminAncestorAdded
        // TODO add your handling code here:
        setResizable(false);
    }//GEN-LAST:event_adminAncestorAdded

    private void reportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportButtonActionPerformed
        // TODO add your handling code here:
        user u = new user();
        Admin a = new Admin();
        int u_id = Integer.parseInt(id2.getText());
        String report_desc = description.getText();
        u.setId(u_id);
        a.report(roleID, reportTable, u, report_desc);
        id2.setText("");
        description.setText("");
        clear_report();
    }//GEN-LAST:event_reportButtonActionPerformed

    private void empRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empRadioActionPerformed
        // TODO add your handling code here:
        roleID = 2;
    }//GEN-LAST:event_empRadioActionPerformed

    private void custRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custRadioActionPerformed
        // TODO add your handling code here:
        roleID = 3;
    }//GEN-LAST:event_custRadioActionPerformed

    private void ofIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ofIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ofIDActionPerformed

    private void update_mealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_mealActionPerformed
        // TODO add your handling code here:
        String name = m_name.getText();
        double price = Double.parseDouble(m_price.getText());
        int quan = Integer.parseInt(m_quan.getText());
        m.setMealId(id);
        m.setMealName(name);
        m.setPrice(price);
        m.setQuantity(quan);
        m.update(m);
        meals.setSelectedIndex(2);        
        m.list(meal_table2);
        clear_updataMeal();
    }//GEN-LAST:event_update_mealActionPerformed

    private void m_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_nameActionPerformed

    private void search_mealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_mealActionPerformed
        // TODO add your handling code here:
        id = Integer.parseInt(search_id1.getText());
        m.setMealId(id);
        m.search(search_table1, m);
        clear_searchMeal();
    }//GEN-LAST:event_search_mealActionPerformed

    private void search_id1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_id1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_id1ActionPerformed

    private void delet_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delet_buttonActionPerformed
        // TODO add your handling code here:
        meals.setSelectedIndex(1);
        row = meal_table2.getSelectedRow();
        id = Integer.parseInt((String) meal_table2.getValueAt(row, 0));
        id_delete1.setText("" + id);
    }//GEN-LAST:event_delet_buttonActionPerformed

    private void list_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_buttonActionPerformed
        m.list(meal_table2);
    }//GEN-LAST:event_list_buttonActionPerformed

    private void update_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_buttonActionPerformed
        // TODO add your handling code here:
        meals.setSelectedIndex(4);
        row = meal_table2.getSelectedRow();
        id = Integer.parseInt((String) meal_table2.getValueAt(row, 0));
        m.setMealId(id);
        m_id.setText("" + id);
        m.send(m, m_name, m_price, m_quan);
    }//GEN-LAST:event_update_buttonActionPerformed

    private void meal_quanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meal_quanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meal_quanActionPerformed

    private void meal_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meal_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meal_priceActionPerformed

    private void meal_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meal_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meal_nameActionPerformed

    private void meal_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meal_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meal_idActionPerformed

    private void updateEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateEmployeeActionPerformed
       String name = e_name.getText();
        String pass = e_pass.getText();
        u.setId(id);
        u.setName(name);
        u.setPassword(pass);
        u.update(u);
        e.update(u);
        emp_mange.setSelectedIndex(2);        
        e.list(emp_table);
        clear_update();
    }//GEN-LAST:event_updateEmployeeActionPerformed

    private void e_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e_passActionPerformed

    private void e_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e_nameActionPerformed

    private void searchEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchEmployeeActionPerformed
        // TODO add your handling code here:
        id = Integer.parseInt(search_idemp.getText());
        u.setId(id);
        e.search(search_emp, u);
        clear_search();
    }//GEN-LAST:event_searchEmployeeActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
         emp_mange.setSelectedIndex(1);
        row = emp_table.getSelectedRow();
        id = Integer.parseInt((String) emp_table.getValueAt(row, 0));
        id_delete.setText("" + id);
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        emp_mange.setSelectedIndex(4);
        row = emp_table.getSelectedRow();
        id = Integer.parseInt((String) emp_table.getValueAt(row, 0));
        u.setId(id);
        e_id.setText("" + id);
        e.send(u, e_name, e_pass);
    }//GEN-LAST:event_updateButtonActionPerformed

    private void listButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listButtonActionPerformed
        e.list(emp_table);  
    }//GEN-LAST:event_listButtonActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        u.setId(id);
        u.delete(u);
        e.delete(u);
        emp_mange.setSelectedIndex(2);        
        e.list(emp_table);
        clear_delete();
    }//GEN-LAST:event_deleteActionPerformed

    private void emp_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_addActionPerformed
        // TODO add your handling code here:
       id = Integer.parseInt(emp_id.getText());
        String name = emp_name.getText();
        String pass = emp_pass.getText();
        u.setId(id);
        u.setName(name);
        u.setPassword(pass);
        u.add(u, 2);
        e.add(u);
        emp_mange.setSelectedIndex(2);
        e.list(emp_table);
        clear_data();
    }//GEN-LAST:event_emp_addActionPerformed

    private void meal_add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meal_add1ActionPerformed
        // TODO add your handling code here:
        id = Integer.parseInt(meal_id.getText());
        String name = meal_name.getText();
        double price = Double.parseDouble(meal_price.getText());
        int quan = Integer.parseInt(meal_quan.getText());
        int ad_id = Integer.parseInt(a_id.getText());
        m.setMealId(id);
        m.setMealName(name);
        m.setPrice(price);
        m.setQuantity(quan);
        a.setId(ad_id);
        m.add(m,a);
        meals.setSelectedIndex(2);        
        m.list(meal_table2);
        clear_addMeal();
    }//GEN-LAST:event_meal_add1ActionPerformed

    private void delete_mealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_mealActionPerformed
        // TODO add your handling code here:
        m.setMealId(id);
        m.delete(m);
        meals.setSelectedIndex(2);        
        m.list(meal_table2);
        clear_deleteMeal();
    }//GEN-LAST:event_delete_mealActionPerformed

    private void add_offerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_offerActionPerformed
        // TODO add your handling code here:
        id = Integer.parseInt(ofID.getText());
        String detalis = offerDetalis.getText();
        int aid = Integer.parseInt(admID.getText());
        o.setOfferId(id);
        o.setOfferDetails(detalis);
        a.setId(aid);
        a.setOffer(o,a);
        clear_offer();
    }//GEN-LAST:event_add_offerActionPerformed

    private void m_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_priceActionPerformed

    private void emp_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_nameActionPerformed

    private void admIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admIDActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.toBack();
        setVisible(false);
        new Login().toFront();
        new Login().setState(Frame.NORMAL);
        new Login().setVisible(true);
        dispose() ;
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Meal;
    private javax.swing.JPanel Report1;
    private javax.swing.JTextField a_id;
    private javax.swing.JPanel add_emp;
    private javax.swing.JPanel add_emp1;
    private javax.swing.JButton add_offer;
    private javax.swing.JTextField admID;
    private javax.swing.JTabbedPane admin;
    private javax.swing.JButton back;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton custRadio;
    private javax.swing.JButton delet_button;
    private javax.swing.JButton delete;
    private javax.swing.JButton deleteButton;
    private javax.swing.JPanel delete_cust2;
    private javax.swing.JPanel delete_emp;
    private javax.swing.JButton delete_meal;
    private javax.swing.JTextArea description;
    private javax.swing.JTextField e_id;
    private javax.swing.JTextField e_name;
    private javax.swing.JPasswordField e_pass;
    private javax.swing.JRadioButton empRadio;
    private javax.swing.JButton emp_add;
    private javax.swing.JTextField emp_id;
    private javax.swing.JTabbedPane emp_mange;
    private javax.swing.JTextField emp_name;
    private javax.swing.JTextField emp_pass;
    private javax.swing.JTable emp_table;
    private javax.swing.JPanel employee;
    private javax.swing.JTextField id2;
    private javax.swing.JTextField id_delete;
    private javax.swing.JTextField id_delete1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JButton listButton;
    private javax.swing.JButton list_button;
    private javax.swing.JPanel list_cust2;
    private javax.swing.JPanel list_emp;
    private javax.swing.JTextField m_id;
    private javax.swing.JTextField m_name;
    private javax.swing.JTextField m_price;
    private javax.swing.JTextField m_quan;
    private javax.swing.JButton meal_add1;
    private javax.swing.JTextField meal_id;
    private javax.swing.JTextField meal_name;
    private javax.swing.JTextField meal_price;
    private javax.swing.JTextField meal_quan;
    private javax.swing.JTable meal_table2;
    private javax.swing.JTabbedPane meals;
    private javax.swing.JTextField ofID;
    private javax.swing.JPanel offer;
    private javax.swing.JTextField offerDetalis;
    private javax.swing.JButton reportButton;
    private javax.swing.JTable reportTable;
    private javax.swing.JButton searchEmployee;
    private javax.swing.JPanel search_cust1;
    private javax.swing.JPanel search_cust2;
    private javax.swing.JTable search_emp;
    private javax.swing.JTextField search_id1;
    private javax.swing.JTextField search_idemp;
    private javax.swing.JButton search_meal;
    private javax.swing.JTable search_table1;
    private javax.swing.JButton updateButton;
    private javax.swing.JButton updateEmployee;
    private javax.swing.JButton update_button;
    private javax.swing.JButton update_meal;
    // End of variables declaration//GEN-END:variables
}
