/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RestaurantManagementSystem;

import java.awt.Frame;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;

/**
 *
 * @author 20112
 */
public class Employeeframe extends javax.swing.JFrame {

    /**
     * Creates new form Employeeframe
     */
    int id , role_id , row;
    user u = new user ();
    Employee e = new Employee(); 
    customer o = new customer();
    dbconnection c =new dbconnection();
    public Employeeframe() {
        initComponents();
    }
    private void clear_order(){
    e_id.setText(null); 
    c_id.setText(null);
    meal_id.setText(null);
    quantity.setText(null);
    price.setText(null);
    
}
private void clear_addcustomer(){
    cust_name.setText(null); 
    cust_id.setText(null);
}
private void clear_deletecustomer(){
    id_delete.setText(null);    
}
 private void clear_searchcustomer(){
    search_id.setText(null);    
}
private void clear_updatacustomer(){
    e_id1.setText(null); 
    c_type.setText(null);
    c_name.setText(null);
    
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        offer = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        off_Table = new javax.swing.JTable();
        showData = new javax.swing.JButton();
        back = new javax.swing.JButton();
        order = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        meal_id = new javax.swing.JTextField();
        set_order = new javax.swing.JButton();
        cancel_odrer = new javax.swing.JButton();
        price = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        meals_table = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        e_id = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        c_id = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        o_id = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        customer = new javax.swing.JPanel();
        cust_manage = new javax.swing.JTabbedPane();
        add_cust = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cust_name = new javax.swing.JTextField();
        cust_id = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cust_add = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        delete_cust = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        id_delete = new javax.swing.JTextField();
        delete = new javax.swing.JButton();
        list_cust = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        cust_table = new javax.swing.JTable();
        butllist = new javax.swing.JButton();
        butupdate = new javax.swing.JButton();
        butdelete = new javax.swing.JButton();
        search_cust = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        search_table = new javax.swing.JTable();
        search_id = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        e_id1 = new javax.swing.JTextField();
        c_name = new javax.swing.JTextField();
        c_type = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(0, 102, 153));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTabbedPane1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTabbedPane1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        offer.setBackground(new java.awt.Color(0, 102, 153));

        off_Table.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        off_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "offer_id", "offer_details"
            }
        ));
        off_Table.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                off_TableComponentRemoved(evt);
            }
        });
        jScrollPane6.setViewportView(off_Table);
        if (off_Table.getColumnModel().getColumnCount() > 0) {
            off_Table.getColumnModel().getColumn(1).setPreferredWidth(300);
        }

        showData.setFont(new java.awt.Font("Teko SemiBold", 1, 18)); // NOI18N
        showData.setForeground(new java.awt.Color(0, 102, 153));
        showData.setText("Show Offers");
        showData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showDataActionPerformed(evt);
            }
        });

        back.setFont(new java.awt.Font("Teko SemiBold", 0, 24)); // NOI18N
        back.setForeground(new java.awt.Color(0, 102, 153));
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout offerLayout = new javax.swing.GroupLayout(offer);
        offer.setLayout(offerLayout);
        offerLayout.setHorizontalGroup(
            offerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(offerLayout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(showData)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, offerLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(offerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(back)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
        offerLayout.setVerticalGroup(
            offerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(offerLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(showData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(back)
                .addGap(37, 37, 37))
        );

        jTabbedPane1.addTab("Offers", offer);

        order.setBackground(new java.awt.Color(0, 102, 153));
        order.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Teko SemiBold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Quantity");
        order.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 305, -1, -1));
        order.add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 309, 44, -1));

        jLabel2.setFont(new java.awt.Font("Teko SemiBold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Meal id");
        order.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 250, -1, -1));
        order.add(meal_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 254, 44, -1));

        set_order.setFont(new java.awt.Font("Teko SemiBold", 0, 18)); // NOI18N
        set_order.setForeground(new java.awt.Color(0, 102, 153));
        set_order.setText("set order");
        set_order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set_orderActionPerformed(evt);
            }
        });
        order.add(set_order, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, -1, -1));

        cancel_odrer.setFont(new java.awt.Font("Teko SemiBold", 0, 18)); // NOI18N
        cancel_odrer.setForeground(new java.awt.Color(0, 102, 153));
        cancel_odrer.setText("Cancel order");
        cancel_odrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_odrerActionPerformed(evt);
            }
        });
        order.add(cancel_odrer, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, -1, -1));
        order.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 51, -1));

        meals_table.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        meals_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Price", "Available Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(meals_table);

        order.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 78, -1, 97));

        jLabel10.setFont(new java.awt.Font("Teko SemiBold", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Total Price");
        order.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, -1, -1));

        jButton3.setFont(new java.awt.Font("Teko SemiBold", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 102, 153));
        jButton3.setText("Show Menu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        order.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 193, -1, -1));

        jLabel3.setFont(new java.awt.Font("Teko SemiBold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Employee ID");
        order.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 26, -1, -1));
        order.add(e_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 30, 50, -1));

        jLabel11.setFont(new java.awt.Font("Teko SemiBold", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Customer ID");
        order.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 26, -1, -1));
        order.add(c_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 51, -1));

        jLabel9.setFont(new java.awt.Font("Teko SemiBold", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Order ID");
        order.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, -1, -1));

        o_id.setFont(new java.awt.Font("Teko SemiBold", 0, 18)); // NOI18N
        order.add(o_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 50, 30));

        jButton2.setFont(new java.awt.Font("Teko SemiBold", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 153));
        jButton2.setText("show orders");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        order.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, 130, -1));

        jTabbedPane1.addTab("Order", order);

        customer.setBackground(new java.awt.Color(0, 102, 153));
        customer.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                customerAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        customer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cust_manage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        add_cust.setBackground(new java.awt.Color(255, 255, 255));
        add_cust.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Teko SemiBold", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 153));
        jLabel4.setText("Customer Name");
        add_cust.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 49, -1, 30));

        jLabel5.setFont(new java.awt.Font("Teko SemiBold", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 153));
        jLabel5.setText("Customer ID");
        add_cust.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 111, 88, 26));

        cust_name.setFont(new java.awt.Font("Teko SemiBold", 0, 15)); // NOI18N
        cust_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cust_nameActionPerformed(evt);
            }
        });
        add_cust.add(cust_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 50, 121, -1));

        cust_id.setFont(new java.awt.Font("Teko SemiBold", 0, 15)); // NOI18N
        add_cust.add(cust_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 110, 121, -1));

        jLabel6.setFont(new java.awt.Font("Teko SemiBold", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 153));
        jLabel6.setText("Customer Type");
        add_cust.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 186, -1, -1));

        cust_add.setFont(new java.awt.Font("Teko SemiBold", 0, 15)); // NOI18N
        cust_add.setForeground(new java.awt.Color(0, 102, 153));
        cust_add.setText("Add");
        cust_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cust_addActionPerformed(evt);
            }
        });
        add_cust.add(cust_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 76, 32));

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Teko SemiBold", 0, 15)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(0, 102, 153));
        jRadioButton1.setText("Markting");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        add_cust.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 182, -1, -1));

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Teko SemiBold", 0, 15)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(0, 102, 153));
        jRadioButton2.setText("Loyalty");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        add_cust.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 182, -1, -1));

        jRadioButton3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Teko SemiBold", 0, 15)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(0, 102, 153));
        jRadioButton3.setText("Reward");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        add_cust.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 182, -1, -1));

        jButton1.setFont(new java.awt.Font("Teko SemiBold", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 153));
        jButton1.setText("Record customer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add_cust.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 130, 30));

        cust_manage.addTab("Add", add_cust);

        delete_cust.setBackground(new java.awt.Color(255, 255, 255));
        delete_cust.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Teko SemiBold", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 153));
        jLabel7.setText("Customer ID");
        delete_cust.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        id_delete.setFont(new java.awt.Font("Teko SemiBold", 0, 15)); // NOI18N
        id_delete.setForeground(new java.awt.Color(0, 102, 153));
        delete_cust.add(id_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 100, -1));

        delete.setFont(new java.awt.Font("Teko SemiBold", 0, 18)); // NOI18N
        delete.setForeground(new java.awt.Color(0, 102, 153));
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        delete_cust.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 89, 46));

        cust_manage.addTab("Delete", delete_cust);

        list_cust.setBackground(new java.awt.Color(255, 255, 255));
        list_cust.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cust_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Name", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(cust_table);

        list_cust.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 479, 94));

        butllist.setFont(new java.awt.Font("Teko SemiBold", 0, 18)); // NOI18N
        butllist.setForeground(new java.awt.Color(0, 102, 153));
        butllist.setText("List");
        butllist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butllistActionPerformed(evt);
            }
        });
        list_cust.add(butllist, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 76, 37));

        butupdate.setFont(new java.awt.Font("Teko SemiBold", 0, 18)); // NOI18N
        butupdate.setForeground(new java.awt.Color(0, 102, 153));
        butupdate.setText("update");
        butupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butupdateActionPerformed(evt);
            }
        });
        list_cust.add(butupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, 37));

        butdelete.setFont(new java.awt.Font("Teko SemiBold", 0, 18)); // NOI18N
        butdelete.setForeground(new java.awt.Color(0, 102, 153));
        butdelete.setText("delete");
        butdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butdeleteActionPerformed(evt);
            }
        });
        list_cust.add(butdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, -1, 37));

        cust_manage.addTab("List", list_cust);

        search_cust.setBackground(new java.awt.Color(255, 255, 255));
        search_cust.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Name", "Password"
            }
        ));
        jScrollPane5.setViewportView(search_table);

        search_cust.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 439, 94));

        search_id.setFont(new java.awt.Font("Teko SemiBold", 0, 18)); // NOI18N
        search_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_idActionPerformed(evt);
            }
        });
        search_cust.add(search_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 95, 30));

        jLabel13.setFont(new java.awt.Font("Teko SemiBold", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 153));
        jLabel13.setText("Customer ID");
        search_cust.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 91, 30));

        search.setFont(new java.awt.Font("Teko SemiBold", 0, 18)); // NOI18N
        search.setForeground(new java.awt.Color(0, 102, 153));
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        search_cust.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 80, 40));

        cust_manage.addTab("Search", search_cust);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setFont(new java.awt.Font("Teko SemiBold", 0, 11)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Teko SemiBold", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 153));
        jLabel17.setText("Customer ID");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        jLabel18.setFont(new java.awt.Font("Teko SemiBold", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 102, 153));
        jLabel18.setText("Customer Name");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        jButton6.setFont(new java.awt.Font("Teko SemiBold", 0, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 102, 153));
        jButton6.setText("Update");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, -1, -1));

        e_id1.setEditable(false);
        e_id1.setFont(new java.awt.Font("Teko SemiBold", 0, 16)); // NOI18N
        e_id1.setForeground(new java.awt.Color(0, 102, 153));
        jPanel1.add(e_id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 143, -1));

        c_name.setFont(new java.awt.Font("Teko SemiBold", 0, 16)); // NOI18N
        c_name.setForeground(new java.awt.Color(0, 102, 153));
        c_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_nameActionPerformed(evt);
            }
        });
        jPanel1.add(c_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 143, -1));
        jPanel1.add(c_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 143, 25));

        jLabel8.setFont(new java.awt.Font("Teko SemiBold", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 153));
        jLabel8.setText("Customer Type ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, 25));

        cust_manage.addTab("Update ", jPanel1);

        customer.add(cust_manage, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 550, 400));

        jTabbedPane1.addTab("Customer", customer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTabbedPane1AncestorAdded
        // TODO add your handling code here:
        setResizable(false);
    }//GEN-LAST:event_jTabbedPane1AncestorAdded

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Meals m = new Meals ();
        m.list(meals_table);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cancel_odrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_odrerActionPerformed
        // TODO add your handling code here:
        Order o1 = new Order();
        int order_id =Integer.parseInt(o_id.getText());
        o1.setId(order_id);
        o1.cancel_odrer(o1);
    }//GEN-LAST:event_cancel_odrerActionPerformed

    private void set_orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set_orderActionPerformed
        // TODO add your handling code here:
        int m_id =Integer.parseInt(meal_id.getText());
        int quan =Integer.parseInt(quantity.getText());
        int emp_id =Integer.parseInt(e_id.getText());
        int cust_id =Integer.parseInt(c_id.getText());
        Order o = new Order();
        Employee e= new Employee();
        Meals m = new Meals ();
        customer c= new customer ();
        o.setQuantity(quan);
        e.setId(emp_id);
        m.setMealId(m_id);
        c.setId(cust_id);
        float total_p = o.totalPrice(m, o);
        price.setText(""+total_p);
        o.setOrder(o, e, m, c);
        //       float totalll = o.setOrder(o, e, m, c);
        //       total.setText(""+totalll);
        //      clear_order();
    }//GEN-LAST:event_set_orderActionPerformed

    private void customerAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_customerAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_customerAncestorAdded

    private void c_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_nameActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String name = c_name.getText();
        int cust_type = Integer.parseInt(c_type.getText());
        u.setId(id);
        u.setName(name);
        u.setRole_id(cust_type);
        u.update(u);
        o.update(u);
        cust_manage.setSelectedIndex(2);
        o.list(cust_table);
        clear_updatacustomer();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        id = Integer.parseInt(search_id.getText());
        u.setId(id);
        o.search(search_table, u);
        clear_searchcustomer();
    }//GEN-LAST:event_searchActionPerformed

    private void search_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_idActionPerformed

    private void butdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butdeleteActionPerformed
        cust_manage.setSelectedIndex(1);
        row = cust_table.getSelectedRow();
        id =Integer.parseInt((String) cust_table.getValueAt(row, 0));
        id_delete.setText(""+id);
    }//GEN-LAST:event_butdeleteActionPerformed

    private void butupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butupdateActionPerformed
        cust_manage.setSelectedIndex(4);
        row = cust_table.getSelectedRow();
        id =Integer.parseInt((String) cust_table.getValueAt(row, 0));
        u.setId(id);
        c_id.setText(""+id);
        o.send(u, c_name, c_type);
    }//GEN-LAST:event_butupdateActionPerformed

    private void butllistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butllistActionPerformed
        o.list(cust_table);
    }//GEN-LAST:event_butllistActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        u.setId(id);
        u.delete(u);
        o.delete(u);
        cust_manage.setSelectedIndex(2);
        o.list(cust_table);
        clear_deletecustomer();
    }//GEN-LAST:event_deleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose() ;
        this.toBack();
        new customerframe().setVisible(true);
        new Employeeframe().setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        role_id=3;
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        role_id=2;
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        role_id=1;
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void cust_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cust_addActionPerformed
        // TODO add your handling code here:

        id =Integer.parseInt(cust_id.getText());
        String name = cust_name.getText();
        u.setId(id);
        u.setName(name);
        u.setRole_id(role_id);
        u.add(u, 3);
        o.add(u);
        cust_manage.setSelectedIndex(2);
        o.list(cust_table);
        clear_addcustomer();
    }//GEN-LAST:event_cust_addActionPerformed

    private void cust_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cust_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cust_nameActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.toBack();
        setVisible(false);
        new Login().toFront();
        new Login().setState(Frame.NORMAL);
        new Login().setVisible(true);
        dispose() ;
    }//GEN-LAST:event_backActionPerformed

    private void showDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showDataActionPerformed
        // TODO add your handling code here:
        Employee e = new Employee();
        e.showoffer(off_Table);
    }//GEN-LAST:event_showDataActionPerformed

    private void off_TableComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_off_TableComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_off_TableComponentRemoved

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        new showorder().setVisible(true);
       
        new Employeeframe().setVisible(false);
        
        
    }//GEN-LAST:event_jButton2ActionPerformed
public void close(){
 
 WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
 Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
 
 }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employeeframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employeeframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employeeframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employeeframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employeeframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel add_cust;
    private javax.swing.JButton back;
    private javax.swing.JButton butdelete;
    private javax.swing.JButton butllist;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton butupdate;
    private javax.swing.JTextField c_id;
    private javax.swing.JTextField c_name;
    private javax.swing.JTextField c_type;
    private javax.swing.JButton cancel_odrer;
    private javax.swing.JButton cust_add;
    private javax.swing.JTextField cust_id;
    private javax.swing.JTabbedPane cust_manage;
    private javax.swing.JTextField cust_name;
    private javax.swing.JTable cust_table;
    private javax.swing.JPanel customer;
    private javax.swing.JButton delete;
    private javax.swing.JPanel delete_cust;
    private javax.swing.JTextField e_id;
    private javax.swing.JTextField e_id1;
    private javax.swing.JTextField id_delete;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel list_cust;
    private javax.swing.JTextField meal_id;
    private javax.swing.JTable meals_table;
    private javax.swing.JTextField o_id;
    private javax.swing.JTable off_Table;
    private javax.swing.JPanel offer;
    private javax.swing.JPanel order;
    private javax.swing.JTextField price;
    private javax.swing.JTextField quantity;
    private javax.swing.JButton search;
    private javax.swing.JPanel search_cust;
    private javax.swing.JTextField search_id;
    private javax.swing.JTable search_table;
    private javax.swing.JButton set_order;
    private javax.swing.JButton showData;
    // End of variables declaration//GEN-END:variables
}
